package io.seunwater.openseun.common;

public enum ProjectType {
    EFFICIENT_COOK_STOVE,
    HOUSEHOLD_COOL_STOVE,
    CLEAN_DRINKING_WATER,
    REDUCED_DEFORESTATION,
    TREES_AND_FORESTRY,
    BIOMASS,
    HOUSEHOLD_SOLAR_COOKER,
    WIND_POWER,
    SOLAR_POWER,
    HYDRO_POWER,
    LAND_FILL_GAS_AND_POWER_GENERATION,
    GEOTHERMAL
}
